#!/bin/bash
#
# A simple framework for regression testing the convert (ctest) script
#
# Returns the number of failed test cases.
#
# Format of a test:
#     test 'command' 'input file name' 'expected output file name' 'expected std error file name'
#
# Some example test cases are given. You should add more test cases.
#
# CAUTION: Uses temporary files named test_err.txt and test_out.txt
# Sam Scott, McMaster University, 2024
#
declare -i tc=0
declare -i fails=0

############################################
# Run a single test. Runs a given command 
# to check the return value, stdout, and stderr
#
# GLOBALS: tc, fails
# PARAMS: $1 = command
#         $2 = input file name
#         $3 = expected std output file name
#         $4 = expected std error file name
#
# Assumes return value should be 0 if the
# std error file is empty. Otherwise it 
# should be 1.
#
# OUTPUTS: An pass/fail report showing the
# difference between expected and actual
# output on a failure (diff command)
############################################
test() {
    tc=tc+1

    local COMMAND=$1
    local INP=$2
    local EX_OUT=$3
    local EX_ERR=$4 

    EX_RET=1
    if [[ $(cat $EX_ERR) = "" ]]; then
        EX_RET=0
    fi
    $COMMAND < $INP > test_out.txt 2> test_err.txt
    RET=$?
    if [[ $RET != $EX_RET ]]; then
        echo "TC $tc Failed"
        echo "Returned $RET"
        echo "-----------"
        fails=$fails+1
        return
    fi
    DIFF=$(diff test_out.txt $EX_OUT)
    if [[ $DIFF != '' ]]; then
        echo "TC $tc Failed Standard Output"
        echo "$DIFF"
        echo "-----------"
        fails=$fails+1
        return
    fi
    DIFF=$(diff test_err.txt $EX_ERR)
    if [[ $DIFF != '' ]]; then
        echo "TC $tc Failed Standard Error"
        echo "$DIFF"
        echo "-----------"
        fails=$fails+1
        return
    fi

    echo "TC $tc Passed"
}

# Compile the C program with gcov enabled
gcc -o match -fprofile-arcs -ftest-coverage test_memoryMatch.c
if [ $? -ne 0 ]; then
    echo "Compilation failed."
    exit 1
fi

# Test cases
test './match' 'inp_max_tries.txt' 'ex_out_max_tries.txt' 'empty.txt'
test './match' 'inp_quit1.txt' 'out_quit1.txt' 'empty.txt'
test './match' 'inp_quit2.txt' 'out_quit2.txt' 'empty.txt'


#generate the gcov report
if [ -f "match-test_memoryMatch.gcno" ]; then
    mv match-test_memoryMatch.gcno test_memoryMatch.gcno
fi

if [ -f "match-test_memoryMatch.gcda" ]; then
    mv match-test_memoryMatch.gcda test_memoryMatch.gcda
fi

# Clean up
rm -f *.gcda *.gcno match
rm test_err.txt test_out.txt

# return code
exit $fails