name: CI - Baddie-Or-Not Personality Test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Make all test scripts executable
      run: |
        chmod +x maze_test_script
        chmod +x test_scriptMemory
        chmod +x wordle_test_script
        chmod +x hangman_test_script.sh

    - name: Make all files executable
      run: |
        make
  
    - name: Run Wordle Test Script
      run: |
        ./wordle_test_script > wordle_test_results.txt

    - name: Run Hangman Test Script
      run: |
        ./hangman_test_script.sh > hangman_test_results.txt
        gcov hangman-test.c > hangman_convert_coverage.txt

    - name: Run Memory Match Test Script
      run: |
        make match
        ./test_scriptMemory > memoryMatch_test_results.txt
        gcov test_memoryMatch.c > memoryMatch_convert_coverage.txt
        
    - name: Run Maze Test Script
      run: |
        gcc -o maze --coverage maze.c
        ./maze_test_script > maze_test_results.txt
        gcov maze.c > maze_convert_coverage.txt

    - name: Upload Wordle Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Wordle Test Results
        path: wordle_test_results.txt
    - name: Upload Wordle Coverage Result
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Wordle Coverage Results
        path: |
          gcov_wordle_output.txt
    - name: Upload Hangman Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Hangman Test Results
        path: hangman_test_results.txt
    - name: Upload Hangman Coverage Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Hangman Coverage Results
        path: |
          hangman_convert_coverage.txt
          hangman_main_coverage.txt
    - name: Upload Memory Match Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Memory Match Test Results
        path: memoryMatch_test_results.txt
    - name: Upload Memory Match Coverage Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Memory Match Coverage Results
        path: |
          memoryMatch_convert_coverage.txt
          memoryMatch_main_coverage.txt
    - name: Upload Maze Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Maze Test Results
        path: maze_test_results.txt
    - name: Upload Maze Coverage Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Maze Coverage Results
        path: |
          maze_convert_coverage.txt
          maze_main_coverage.txt
