name: CI - Baddie-Or-Not Personality Test

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Make all test scripts executable
      run: |
        chmod +x maze_test_script
        chmod +x wordle_test_script
        chmod +x hangman_test_script.sh

    - name: Make all files executable
      run: |
        make
  
    - name: Run Wordle Test Script
      run: |
        ./wordle_test_script > wordle_test_results.txt
        gcov wordle.c > wordle_convert_coverage.txt

    - name: Run Hangman Test Script
      run: |
        ./hangman_test_script > hangman_test_results.txt
        gcov hangman-beta.c > hangman_convert_coverage.txt
        
    - name: Run Maze Test Script
      run: |
        ./maze_test_script > maze_test_results.txt
        gcov maze.c > maze_convert_coverage.txt

    - name: Upload Wordle Test Results and Coverage
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Wordle Test Results
        path: wordle_test_results.txt
    - name: Upload Wordle Coverage Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Wordle Coverage Results
        path: |
          wordle_convert_coverage.txt
          wordle_main_coverage.txt

    - name: Upload Hangman Test Results and Coverage
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Hangman Test Results
        path: hangman_test_results.txt
    - name: Upload Hangman Coverage Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Hangman Coverage Results
        path: |
          hangman_convert_coverage.txt
          hangman_main_coverage.txt
